spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripbee?serverTimezone=UTC
    username: ssafy
    password: ssafy
#    type: org.apache.commons.dbcp2.BasicDataSource

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: studymail0128@gmail.com
    password: rrhmfpkvyxntopwr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  type-aliases-package: com.ssafy.*.domain.*.dto, com.ssafy.*.domain.*.entity
  mapper-locations: mapper/*.xml

logging:
  level:
    com:
      ssafy: debug
    root: info

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

  expired-min:
    access: 60   # 액세스 토큰 만료제한시간 60분 (1시간)
    refresh: 10080  # 리프레쉬 토큰 만료제한시간 10080분 (7일)
